FROM python:3.10-slim AS builder

RUN apt update && apt install --no-install-recommends -y gcc libc6-dev libopenblas-dev ninja-build build-essential wget git

WORKDIR /workspace

RUN git clone https://github.com/petals-infra/chat.petals.dev.git

WORKDIR /workspace/chat.petals.dev

RUN pip install -r requirements.txt --no-cache-dir --upgrade pip && \
    pip cache purge

COPY _chat_config.py .
