FROM python:3.10-slim AS builder

RUN apt update && apt install --no-install-recommends -y gcc libc6-dev libopenblas-dev ninja-build build-essential wget git

WORKDIR /workspace

RUN git clone https://github.com/petals-infra/health.petals.dev

WORKDIR /workspace/health.petals.dev

# Hack fix for pydantic error
COPY _health_data_structures.py ./data_structures.py

RUN pip install -r requirements.txt --no-cache-dir --upgrade pip && \
    pip cache purge

COPY _health_config.py .
