# syntax=docker/dockerfile:1
FROM debian:bullseye AS builder

RUN apt-get update && apt-get install --yes git cmake g++ libgomp1

RUN mkdir /workspace
WORKDIR /workspace
RUN git clone https://github.com/ggerganov/llama.cpp.git

# WORKDIR /workspace/llama.cpp

# # GGML_RPC=ON: Builds RPC support
# # BUILD_SHARED_LIBS=OFF: Don't rely on shared libraries like libggml
# # use -DGGML_CUDA=ON for GPU support
# RUN cmake . -DGGML_RPC=ON -DBUILD_SHARED_LIBS=OFF -DGGML_DEBUG=1 
# RUN cmake --build . --config Release --parallel 4

# RUN ldd bin/rpc-server

#FROM debian:bullseye

#RUN apt update && apt install libgomp1 -y

#COPY --from=builder /workspace/llama.cpp/bin/rpc-server /rpc-server

#WORKDIR /workspace

COPY run_rpc.sh .
COPY build.sh .

RUN chmod +x /workspace/run_rpc.sh
RUN chmod +x /workspace/build.sh
