FROM python:3.12-slim

RUN apt update && apt install -y gcc unzip curl

WORKDIR /workspace/kalavai

COPY . .
RUN pip3 install -e .
RUN pip3 install -r gui/requirements.txt

WORKDIR /workspace/kalavai/gui
CMD ["reflex", "run"]