server:
  platform: "amd64"
  ip_address: null
  location: null
  name: "kalavai_cluster"
  mtu: ""
  watcher_image_tag: "2026.7.6"
  host_root_path: "/hostroot"

core:
  # Deploy systems
  deploy: []
  # - rocm
  # - monitoring
  # - istio
  # "Kalavai API"
  clickhouse:
    endpoint: "https://clickhouse.svc"
    password: "password"
    port: 8443
    username: default
  kalavai_api_version: null
  # "Global"
  kalavai_role_label: "kalavai/role"
  # "Watcher is shared pool"
  watcher_is_shared_pool: "True"
  watcher_resources_memory: 1Gi
  watcher_resources_cpu: 1
  watcher_replicas: 1
  # "Prometheus and opencost"
  prometheus_service_name: prometheus-kube-prometheus-prometheus
  prometheus_namespace: monitoring
  prometheus_port: 9090
  # "Prometheus server retention"
  prometheus_server_retention: "30d"
  prometheus_disk_size: "8Gi"
  prometheus_externalLabel_cluster: kalavai-prod
  # Thanos
  thanos_service_name: thanos-query-frontend
  thanos_namespace: monitoring
  thanos_port: 9090
  thanos_s3_access_key: ""
  thanos_s3_secret_key: ""
  thanos_s3_endpoint: s3.fr-par.scw.cloud
  thanos_s3_region: fr-par
  thanos_s3_bucket: prod-monitoring
  thanos_query_replicas: 1
  thanos_query_frontend_replicas: 1
  thanos_store_replicas: 1
  thanos_bucket_replicas: 1
  # Thanos retention on s3
  thanos_retention_raw: "30d"
  thanos_retention_5m: "45d"
  thanos_retention_1h: "70d"
  # GPU
  gpu_deviceSplitCount: 4
  gpu_nodeSchedulerPolicy : binpack
  gpu_gpuSchedulerPolicy : binpack

pool:
  dns_api_token: null
  dns_email: "info@kalavai.net"
  dns_subdomain: "spaces.kalavai.net"
  dns_cert_manager_namespace: "cert-manager"
  dns_ingress_controller_namespace: "kube-system"
  