services:
  kalavai_ui:
    container_name: kalavai_ui
    image: ghcr.io/kalavai-net/kalavai-ui:{{gui_version}}
    platform: linux/amd64
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
    network_mode: host
    environment:
    - NEXT_PUBLIC_KALAVAI_API_URL={{kalavai_api_url}}
    - PORT={{gui_frontend_port}}
    {% if protected_access %}
    - NEXT_PUBLIC_ACCESS_KEY={{protected_access}}
    {% endif %}
    volumes:
      - "{{path}}:/root/.cache/kalavai"
    restart: always

