# Global traefik config 
# watcher cannot install because of namespace issues??
# apiVersion: helm.cattle.io/v1
# kind: HelmChartConfig
# metadata:
#   name: traefik
#   namespace: kube-system
# spec:
#   valuesContent: |-
#     # service:
#     #   externalTrafficPolicy: Local

#     replicas: 1
#     tolerations:
#       - key: "node-role.kubernetes.io/control-plane"
#         operator: "Exists"
#         effect: "NoSchedule"
#       - key: "node-role.kubernetes.io/master"
#         operator: "Exists"
#         effect: "NoSchedule"
#     nodeSelector:
#       node-role.kubernetes.io/control-plane: "true"
#     podAntiAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#         - labelSelector:
#             matchExpressions:
#               - key: app.kubernetes.io/name
#                 operator: In
#                 values:
#                   - traefik
#           topologyKey: "kubernetes.io/hostname"
---
# Namespace creation with custom labels
apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}
  labels:
    istio.io/use-waypoint: {{ namespace }}-waypoint
    istio.io/dataplane-mode: ambient
    istio.io/ingress-use-waypoint: "true"
---
# Per user space service account and binding to access downstream API
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader-sa
  namespace: {{ namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ namespace }}-reader-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ namespace }}-reader-binding
subjects:
- kind: ServiceAccount
  name: reader-sa
  namespace: {{ namespace }}
roleRef:
  kind: ClusterRole # refers to cluster wide cluster role
  name: {{ namespace }}-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  labels:
    istio.io/waypoint-for: service # service, workload, all, none
  name: {{ namespace }}-waypoint
  namespace: {{ namespace }}
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
---
