FROM boinc/client:nvidia

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y iputils-ping

WORKDIR /workspace

COPY setup_workers.sh .
COPY wait_for_hosts.sh .
COPY merge.sh .
COPY global_prefs_override.xml .

RUN chmod +x /workspace/merge.sh
RUN chmod +x /workspace/setup_workers.sh
RUN chmod +x /workspace/wait_for_hosts.sh

WORKDIR /var/lib/boinc
