# All options: https://docs.axolotl.ai/docs/config-reference.html

base_model: NousResearch/Llama-3.2-1B
# Automatically upload checkpoint and final model to HF
hf_use_auth_token: true

# useful to resume training runs
save_only_model: false

save_safetensors: true
load_in_8bit: true
load_in_4_bit: false

# Ray parameters
use_ray: true
ray_num_workers: 1
resources_per_worker:
  GPU: 1

datasets:
  - path: teknium/GPT4-LLM-Cleaned
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir: ./outputs/lora-out

adapter: lora
lora_model_dir:

sequence_len: 2048
sample_packing: true
eval_sample_packing: true

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

gradient_accumulation_steps: 2
micro_batch_size: 2
num_epochs: 1
optimizer: adamw_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: false

loss_watchdog_threshold: 5.0
loss_watchdog_patience: 3

warmup_ratio: 0.1
evals_per_epoch: 4
saves_per_epoch: 1

deepspeed: zero3.json
weight_decay: 0.0
special_tokens:
  pad_token: "<|end_of_text|>"


# save_first_step: true  # uncomment this to validate checkpoint saving works with your config